# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 200dfb56d59f34ba3054003a0f47a41fcb973518f847c8ab730d01e918ba7bc6ed42a2b89823588f05ebd74f81a917ab813097777da7dd98a664c8e3de175f89

test:
  secret_key_base: fc8f229996332c95c738b0d237986d8000563f0b8c9187ae2b3742e2e36c4d4f6ad86e04b1df4e7988331a2929e7eec889c8c52155b13c2407a4386376802453

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
